### ISSUE TITLE
Subsequent steps are failing

### ISSUE THREAD

**Issue by attilaolah** [wercker/step-setup-go-workspace#5]
A simple `wercker.yml` like this:

```yml
box: golang

build:
  steps:
    - setup-go-workspace

    - script:
        name: go version
        code: |
          go version
```

will fail at the `go version` step. However, removing the `setup-go-workspace` step fixes the issue.

Same thing happens both online running Ewok (5) and with the [new `wercker` CLI](/wercker/sentcli).
